# -*- coding: utf-8 -*-
"""Pandas1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bne-0YmOx3d58KqkhsoZK-r5UF2DOXlM

#Loading data into pandas
"""

import pandas as pd

# load csv
df = pd.read_csv('pokemon_data.csv')
df.head()

df.head(3)

# load xlsx
df_xlsx = pd.read_excel('pokemon_data.xlsx')
df.head(1)

# load txt file
df_txt = pd.read_csv('pokemon_data.txt', delimiter="\t")
df_txt.head(1)

"""#Reading the data """

#reading headers/columns
print(df.columns)

#read a particular columns
# df.Names also works
print(df['Name'])
#top 5 names
#  df['Name'][0:5]

#read rows
# print(df.head(3))
print(df.iloc[2:4])

#specific position
print(df.iloc[2,1])

# 
for index,row in df.iterrows():
    print(index,row['Name'])

# loc function
df.loc[df['Type 1']=='Fire']

"""#Sorting/Describing Data"""

df.describe()

df.shape

df.sort_values('Name', ascending=True)
# use implace="True" if manipulate data in this

df.sort_values(['Type 1','HP'], ascending=[1,0])

"""#Make changes to the data"""

# adding a column 
df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Def'] + df['Speed'] + df['Speed']
df.head(2)

# drop a specific collumns

df = df.drop(columns='Total')
df.head(2)

df['Total'] = df.iloc[:,4:10].sum(axis = 1)
df.head(2)

# altering columns positions
cols = df.columns.to_list()
df = df[cols[0:4]+ [cols[-1]]+ cols[4:12]]
df.head(2)

"""#Saving our data"""

df.to_csv('modified.csv')
# if you don't need in dex use index=False

df.to_excel('modefied.xlsx')

df.to_csv('modified.txt',index=False,sep='\t')

"""#Filtering data"""

new_df = df.loc[(df['Type 1']=='Grass') & (df['Type 2']=='Poison')]
new_df

# get rid of the index
new_df.reset_index(drop=True,inplace=True)
new_df

new_df[new_df['Name'].str.contains("Mega")]

# using regex (regular expressions) 
import re
# flag is used for ignore case
new_df.loc[new_df['Name'].str.contains('Mega|bell',flags = re.I,regex = True)]

"""#Conditional changes"""

# important
df.loc[df['Type 1']=='Fire','Type 1'] = 'Flame'
df.head(5)
# df.loc[df['Type 1']=='Fire',[HP,Speed]] = [100,20]   THIS IS also a way

"""#Aggregate statistics"""

df.groupby(df['Type 1']).mean()

# df.groubby(df[col_name]).mean.sort_values('col_name_to sort',asending==False)

df.groupby(df['Type 1']).sum()

df['count'] = 1
df.groupby(df['Type 1']).count()['count']

# use ,chunksize if reading large data